# ---+ Extensions
# ---++ PageOptimizerPlugin
# This is the configuration used by the <b>PageOptimizerPlugin</b>.

# **BOOLEAN**
# If enabled, the final markup as generated by foswiki is cleaned up.
# Disable this flag for debugging foswiki's own html output.
$Foswiki::cfg{PageOptimizerPlugin}{CleanUpHTML} = 1;

1;
